export const ADD_TASK="ADD_TASK"
export const EDIT_TASK="EDIT_TASK"
export const EDIT_DATA="EDIT_DATA"
export const OPEN_MODAL="OPEN_MODAL"
export const CHANGE_METHOD="CHANGE_METHOD"
export const DELETE_DATA="DELETE_DATA"